### ISSUE TITLE
NotADirectoryError and Fail to load the node -- closed

### ISSUE THREAD

**Issue by aicoder2048** [WASasquatch/was-node-suite-comfyui#347]
I made an update on comfyui and nodes, then I somehow fail to load the was-node-suite-comfyui node. I got the following error, and have no clue how to fix it. 

Maybe someone with extensive experience could come to help, thanks a lot !

ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\sean2092\miniconda3\envs\ComfyUI\Lib\site-packages\pip\_internal\cli\base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
             ^^^^^^^^^^^^^^^
  File "C:\Users\sean2092\miniconda3\envs\ComfyUI\Lib\site-packages\pip\_internal\commands\freeze.py", line 98, in run
    for line in freeze(
  File "C:\Users\sean2092\miniconda3\envs\ComfyUI\Lib\site-packages\pip\_internal\operations\freeze.py", line 43, in freeze
    req = FrozenRequirement.from_dist(dist)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sean2092\miniconda3\envs\ComfyUI\Lib\site-packages\pip\_internal\operations\freeze.py", line 238, in from_dist
    req, comments = _get_editable_info(dist)
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sean2092\miniconda3\envs\ComfyUI\Lib\site-packages\pip\_internal\operations\freeze.py", line 165, in _get_editable_info
    vcs_backend = vcs.get_backend_for_dir(location)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sean2092\miniconda3\envs\ComfyUI\Lib\site-packages\pip\_internal\vcs\versioncontrol.py", line 238, in get_backend_for_dir
    repo_path = vcs_backend.get_repository_root(location)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sean2092\miniconda3\envs\ComfyUI\Lib\site-packages\pip\_internal\vcs\git.py", line 501, in get_repository_root
    r = cls.run_command(
        ^^^^^^^^^^^^^^^^
  File "C:\Users\sean2092\miniconda3\envs\ComfyUI\Lib\site-packages\pip\_internal\vcs\versioncontrol.py", line 650, in run_command
    return call_subprocess(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\sean2092\miniconda3\envs\ComfyUI\Lib\site-packages\pip\_internal\utils\subprocess.py", line 141, in call_subprocess
    proc = subprocess.Popen(
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\sean2092\miniconda3\envs\ComfyUI\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\sean2092\miniconda3\envs\ComfyUI\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NotADirectoryError: [WinError 267] 目录名称无效。
Traceback (most recent call last):
  File "C:\Apps\ComfyUI\ComfyUI\nodes.py", line 1887, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Apps\ComfyUI\ComfyUI\custom_nodes\was-node-suite-comfyui\__init__.py", line 1, in <module>
    from .WAS_Node_Suite import NODE_CLASS_MAPPINGS
  File "C:\Apps\ComfyUI\ComfyUI\custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py", line 14103, in <module>
    if 'opencv-python' in packages() or 'opencv-python-headless' in packages():
                          ^^^^^^^^^^
  File "C:\Apps\ComfyUI\ComfyUI\custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py", line 336, in packages
    return [( r.decode().split('==')[0] if not versions else r.decode() ) for r in subprocess.check_output([sys.executable, '-s', '-m', 'pip', 'freeze']).split()]
                                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sean2092\miniconda3\envs\ComfyUI\Lib\subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sean2092\miniconda3\envs\ComfyUI\Lib\subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\Users\\sean2092\\miniconda3\\envs\\ComfyUI\\python.exe', '-s', '-m', 'pip', 'freeze']' returned non-zero exit status 2.

Cannot import C:\Apps\ComfyUI\ComfyUI\custom_nodes\was-node-suite-comfyui module for custom nodes: Command '['C:\\Users\\sean2092\\miniconda3\\envs\\ComfyUI\\python.exe', '-s', '-m', 'pip', 'freeze']' returned non-zero exit status 2.

**Comment by WASasquatch** [comment]
Sounds like it was conflict in packages and environments

**Comment by bingwei** [comment]
I fixed this.
I modify pip freeze to pip list, and the error skiped.
```return [( r.decode().split('==')[0] if not versions else r.decode() ) for r in subprocess.check_output([sys.executable, '-s', '-m', 'pip', 'freeze']).split()]``` changed to 
```return [( r.decode().split('==')[0] if not versions else r.decode() ) for r in subprocess.check_output([sys.executable, '-s', '-m', 'pip', 'list']).split()]```

**Comment by WASasquatch** [comment]
That would break all packages checks though.

**Comment by dimroce** [comment]
> I fixed this. I modify pip freeze to pip list, and the error skiped. `return [( r.decode().split('==')[0] if not versions else r.decode() ) for r in subprocess.check_output([sys.executable, '-s', '-m', 'pip', 'freeze']).split()]` changed to `return [( r.decode().split('==')[0] if not versions else r.decode() ) for r in subprocess.check_output([sys.executable, '-s', '-m', 'pip', 'list']).split()]`

thank you i fixed too, just need change "freeze" to "list", in WAS_Node_Suite.py

**Comment by WAS-PlaiLabs** [comment]
It doesn't fix it. It breaks all checks. It's a different format that the code isn't setup to decode.
